# Generated by Django 2.2.15 on 2020-09-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, unique=True)),
                ('Body', models.TextField()),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pub_date', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
